import type { DashboardActivity } from './types';

export const DASHBOARD_ACTIVITY: DashboardActivity[] = [
  {
    id: '1',
    actor: 'Avery Quinn',
    avatarUrl: 'https://i.pravatar.cc/120?u=activity-1',
    action: 'Closed deal · Acme Corp Q3',
    channel: 'Sales',
    region: 'NA',
    priority: 'high',
    impact: '+$24.0k',
    status: 'completed',
    timestamp: '2026-05-30T09:14:00Z',
  },
  {
    id: '2',
    actor: 'Jordan Patel',
    avatarUrl: 'https://i.pravatar.cc/120?u=activity-2',
    action: 'Updated forecast model',
    channel: 'Product',
    region: 'EMEA',
    priority: 'medium',
    impact: '+$8.2k',
    status: 'in_review',
    timestamp: '2026-05-29T16:48:00Z',
  },
  {
    id: '3',
    actor: 'Sasha Romero',
    avatarUrl: 'https://i.pravatar.cc/120?u=activity-3',
    action: 'New audience segment created',
    channel: 'Marketing',
    region: 'NA',
    priority: 'medium',
    impact: '+$4.6k',
    status: 'completed',
    timestamp: '2026-05-29T11:02:00Z',
  },
  {
    id: '4',
    actor: 'Morgan Lee',
    avatarUrl: 'https://i.pravatar.cc/120?u=activity-4',
    action: 'Pending campaign approval',
    channel: 'Marketing',
    region: 'APAC',
    priority: 'low',
    impact: '+$1.1k',
    status: 'pending',
    timestamp: '2026-05-28T18:35:00Z',
  },
  {
    id: '5',
    actor: 'Riley Chen',
    avatarUrl: 'https://i.pravatar.cc/120?u=activity-5',
    action: 'Integration test passed',
    channel: 'Engineering',
    region: 'EMEA',
    priority: 'high',
    impact: '+$12.5k',
    status: 'completed',
    timestamp: '2026-05-28T08:21:00Z',
  },
];
