import fs from 'node:fs';
import path from 'node:path';

const rootDir = process.cwd();
const indexPath = path.resolve(rootDir, 'ai/contracts/index.json');
const activeThemePath = path.resolve(rootDir, 'ai/theme.active.json');
const activeCssPath = path.resolve(rootDir, 'src/themes/active.css');

const args = process.argv.slice(2);
const getArgValue = (flag) => {
  const flagIndex = args.indexOf(flag);
  if (flagIndex === -1 || flagIndex + 1 >= args.length) {
    return null;
  }
  return args[flagIndex + 1];
};

const themeId = getArgValue('--theme');
const mode = getArgValue('--mode') ?? 'system';

if (!themeId) {
  console.error('Missing required argument: --theme <theme-id>');
  process.exit(1);
}

if (!['light', 'dark', 'system'].includes(mode)) {
  console.error('Invalid mode. Allowed values: light, dark, system');
  process.exit(1);
}

const indexJson = JSON.parse(fs.readFileSync(indexPath, 'utf8'));
const themes = Array.isArray(indexJson.themes) ? indexJson.themes : [];
const selectedTheme = themes.find((theme) => theme.id === themeId);

if (!selectedTheme) {
  console.error(`Unknown theme id: ${themeId}`);
  process.exit(1);
}

const selectedCssAbsolutePath = path.resolve(rootDir, selectedTheme.cssPath);
if (!fs.existsSync(selectedCssAbsolutePath)) {
  console.error(`Theme CSS file is missing: ${selectedTheme.cssPath}`);
  process.exit(1);
}

const importTarget = `./${path.basename(selectedTheme.cssPath)}`;
const activeCss = [
  '/* Auto-generated by pnpm theme:apply. */',
  `@import \"${importTarget}\";`,
  '',
].join('\n');

fs.writeFileSync(activeCssPath, activeCss, 'utf8');

const activeThemeJson = {
  themeId,
  mode,
  updatedAt: new Date().toISOString(),
};

fs.writeFileSync(
  activeThemePath,
  `${JSON.stringify(activeThemeJson, null, 2)}\n`,
  'utf8',
);

console.log(`Applied theme '${themeId}' with mode '${mode}'.`);
